application: mit-media-lab
version: 1
runtime: go
api_version: go1

handlers:
- url: /config
  login: admin
  static_files: config.json
  upload: config.json
  application_readable: true

- url: /
  static_files: index.html
  upload: index.html

- url: /s
  static_dir: s

- url: /.*
  script: _go_app
